utils::globalVariables(c("group", "pathway", "padj", "NES", "pval"))
utils::globalVariables(c("x.pos", "y.pos", "newfill"))
utils::globalVariables(c("p1", "p2"))
utils::globalVariables(c("Comparison", "avg_log2FC"))
utils::globalVariables(c("Comparison", "effect_size"))
utils::globalVariables(c("gene", "effect_size", "avg_log2FC", "pval"))
utils::globalVariables(c("pathways_hallmark", "pathways_kegg", "pathways_reactome"))
